# Generated by Django 3.2.18 on 2023-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loaders', '0008_auto_20230501_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Юридическое лицо', 'Юридическое лицо'), ('Физическое лицо', 'Физическое лицо')], max_length=16, verbose_name='Тип контрагента')),
                ('legal_name', models.CharField(max_length=200, unique=True, verbose_name='Юридическое наименование')),
                ('short_name', models.CharField(max_length=100, unique=True, verbose_name='Краткое наименование')),
                ('inn', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('kpp', models.IntegerField(blank=True, null=True, verbose_name='КПП')),
                ('legal_address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Фактический адрес')),
                ('actual_address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Фактический адрес')),
                ('payment_account', models.IntegerField(blank=True, null=True, verbose_name='Расчетный счет')),
                ('correspondent_account', models.IntegerField(blank=True, null=True, verbose_name='Корреспондентский счет')),
                ('bik', models.IntegerField(blank=True, null=True, verbose_name='БИК')),
                ('bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование банка')),
                ('specialization', models.ManyToManyField(related_name='clsspecializations', to='loaders.Specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['short_name'],
            },
        ),
    ]
