# Generated by Django 3.2.18 on 2023-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0001_initial'),
        ('clients', '0003_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='specialization',
            field=models.ManyToManyField(related_name='clsspecializations', to='specializations.Specialization', verbose_name='Специализация'),
        ),
    ]
