# Generated by Django 3.2.18 on 2023-05-16 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50, unique=True, verbose_name='Платежный метод')),
            ],
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisites', models.CharField(max_length=150, verbose_name='Реквизиты оплаты')),
                ('bank', models.CharField(max_length=150, verbose_name='Наименование банка')),
                ('comments', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарии к оплате')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='paymethods.paymenttype', verbose_name='Платежный метод')),
            ],
        ),
    ]
