# Generated by Django 3.2.18 on 2023-05-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Создана'), ('1.1', 'Отменена'), ('2', 'Расставлено'), ('3', 'В работе'), ('4', 'Выполнена'), ('5', 'Подтверждена'), ('6', 'Внутренняя приемка'), ('7', 'Закрыта'), ('8', 'Включена в счет'), ('9', 'Деньги получены')], default='1', max_length=20, verbose_name='Статус заявки')),
            ],
        ),
    ]
