# Generated by Django 3.2.18 on 2023-05-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0008_auto_20230501_1454'),
        ('orders', '0003_auto_20230504_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loaders.paymethodlist'),
        ),
    ]
