# Generated by Django 3.2.18 on 2023-05-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание заявки для исполнителей'),
        ),
        migrations.AddField(
            model_name='order',
            name='description_internal',
            field=models.TextField(blank=True, null=True, verbose_name='Внутреннее описание заявки'),
        ),
    ]
