# Generated by Django 3.2.18 on 2023-05-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20230505_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_method',
        ),
    ]
