# Generated by Django 3.2.18 on 2023-04-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loaders', '0007_alter_loader_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loaders.loader')),
            ],
            options={
                'unique_together': {('loader', 'day')},
            },
        ),
    ]
