# Generated by Django 3.2.18 on 2023-04-15 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0007_alter_loader_passport'),
        ('shedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_call_result', models.CharField(blank=True, max_length=150, null=True, verbose_name='Статус последнего обзвона')),
                ('date_last_call', models.DateField(blank=True, null=True, verbose_name='День последнего обзвона')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Причина отказа работы')),
                ('day_get_last_status', models.DateField(blank=True, null=True)),
                ('loader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='loaders.loader', verbose_name='Грузчик')),
            ],
        ),
    ]
