# Generated by Django 3.2.18 on 2023-04-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0002_callresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
