# Generated by Django 3.2.18 on 2023-04-15 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0003_auto_20230415_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshedule',
            options={'ordering': ['day']},
        ),
    ]
