# Generated by Django 3.2.18 on 2023-05-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=12, unique=True, verbose_name='Серия Номер')),
                ('issued_by', models.CharField(max_length=200, verbose_name='Кем выдан')),
                ('division_code', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('place_of_birth', models.CharField(max_length=50, verbose_name='Место рождения')),
                ('photo_main_page', models.ImageField(blank=True, upload_to='photo/passports/', verbose_name='Фото главной страницы')),
                ('photo_registration', models.ImageField(blank=True, upload_to='photo/passports/', verbose_name='Фото страницы с пропиской')),
            ],
        ),
    ]
