# Generated by Django 3.2.18 on 2023-04-11 05:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=12, unique=True, verbose_name='Серия Номер')),
                ('issued_by', models.CharField(max_length=200, verbose_name='Кем выдан')),
                ('division_code', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('place_of_birth', models.CharField(max_length=50, verbose_name='Место рождения')),
                ('photo_main_page', models.ImageField(blank=True, upload_to='photo/passports/', verbose_name='Фото главной страницы')),
                ('photo_registration', models.ImageField(blank=True, upload_to='photo/passports/', verbose_name='Фото страницы с пропиской')),
            ],
        ),
        migrations.CreateModel(
            name='PayMethodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(max_length=50, unique=True, verbose_name='Платежный метод')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50, unique=True, verbose_name='Тип работы')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisites', models.CharField(max_length=150, verbose_name='Реквизиты оплаты')),
                ('bank', models.CharField(max_length=150, verbose_name='Наименование банка')),
                ('comments', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарии к оплате')),
                ('pay_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='methods', to='loaders.paymethodlist', verbose_name='Платежный метод')),
            ],
        ),
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=18, unique=True, verbose_name='Номер телефона')),
                ('whatsapp', models.CharField(max_length=18, unique=True, verbose_name='WhatsApp')),
                ('photo', models.ImageField(blank=True, upload_to='photo/loaders/', verbose_name='Фото')),
                ('area', models.CharField(choices=[('Заельцовский', 'Заельцовский'), ('Дзержинский', 'Дзержинский'), ('Кировский', 'Кировский'), ('Калининский', 'Калининский'), ('Ленинский', 'Ленинский'), ('Октябрьский', 'Октябрьский'), ('Первомайский', 'Первомайский'), ('Советский', 'Советский'), ('Центральный', 'Центральный '), ('НСО', 'НСО')], max_length=150, verbose_name='Район проживания')),
                ('date_of_employment', models.DateField(auto_now_add=True, verbose_name='Дата приема на работу')),
                ('first_job_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата первой заявки')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, 'Рейтинг не может быть меньше 1!'), django.core.validators.MaxValueValidator(5, 'Рейтинг не может быть выше 5!')], verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True)),
                ('passport', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passport', to='loaders.passport')),
                ('pay_method', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_methods', to='loaders.paymethod', verbose_name='Метод расчета')),
                ('referer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referer', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил')),
                ('specialization', models.ManyToManyField(related_name='specializations', to='loaders.Specialization', verbose_name='Специализация')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loaders.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Грузчик',
                'verbose_name_plural': 'Грузчики',
                'ordering': ['last_name'],
            },
        ),
    ]
