# Generated by Django 3.2.18 on 2023-04-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
    ]
