# Generated by Django 3.2.18 on 2023-04-13 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0002_alter_specialization_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loader',
            name='passport',
        ),
        migrations.AddField(
            model_name='passport',
            name='passport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loaders', to='loaders.loader'),
            preserve_default=False,
        ),
    ]
