# Generated by Django 3.2.18 on 2023-04-13 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0004_alter_passport_passport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='passport',
            new_name='loader',
        ),
    ]
