# Generated by Django 3.2.18 on 2023-04-14 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0005_rename_passport_passport_loader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='loader',
        ),
        migrations.AddField(
            model_name='loader',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='loaders.passport'),
        ),
    ]
