# Generated by Django 3.2.18 on 2023-05-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0007_alter_loader_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loader',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='loaders.passport'),
        ),
        migrations.AlterField(
            model_name='loader',
            name='pay_method',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_methods', to='loaders.paymethod', verbose_name='Метод расчета'),
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='pay_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='loaders.paymethodlist', verbose_name='Платежный метод'),
        ),
    ]
