# Generated by Django 3.2.18 on 2023-05-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0001_initial'),
        ('loaders', '0008_auto_20230501_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loader',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='passports.passport'),
        ),
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
