# Generated by Django 3.2.18 on 2023-05-16 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymethods', '0001_initial'),
        ('orders', '0006_remove_order_pay_method'),
        ('loaders', '0010_auto_20230514_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loader',
            name='pay_method',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_methods', to='paymethods.paymethod', verbose_name='Метод расчета'),
        ),
        migrations.DeleteModel(
            name='PayMethod',
        ),
        migrations.DeleteModel(
            name='PayMethodList',
        ),
    ]
