# Generated by Django 3.2.18 on 2023-05-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
        ('loaders', '0011_auto_20230516_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loader',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.status', verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
